export const exerciseDummy = [
  {
    isUserJoined: true,
    isGuestAllowedByOwner: true,
    title: "아침 헬스 모임",
    date: "05.02",
    day: "목",
    location: "서울 강남구",
    time: "오전 10:00",
    femaleLevel: "초급 ~ 중급",
    maleLevel: "중급 ~ 상급",
    currentPeople: 4,
    maxPeople: 10,
  },
  {
    isUserJoined: false,
    isGuestAllowedByOwner: false,
    title: "저녁 요가 클래스",
    date: "05.04",
    day: "토",
    location: "경기 수원시",
    time: "오후 7:00",
    femaleLevel: "초급",
    maleLevel: "누구나 참여 가능",
    currentPeople: 7,
    maxPeople: 12,
  },
  {
    isUserJoined: true,
    isGuestAllowedByOwner: false,
    title: "주말 필라테스",
    date: "05.06",
    day: "월",
    location: "부산 해운대구",
    time: "오전 8:30",
    femaleLevel: "중급",
    maleLevel: "상급",
    currentPeople: 3,
    maxPeople: 8,
  },
];
