export const exerciseDummy = [
  {
    exerciseId: 1,
    partyName: "아침 헬스 모임",
    buildingAddr: "산성 실내 배드민턴장",
    streetAddr: "서울 강남구",
    date: "2025-05-02",
    startExerciseTime: "10:00:00",
    endExerciseTime: "11:30:00",
    femaleLevel: "초급 ~ 중급",
    maleLevel: "중급 ~ 상급",
    nowMemberCnt: 4,
    maxMemberCnt: 10,
    includeParty: true,
    includeExercise: false,
    isFavorite: true,
  },
  {
    exerciseId: 2,
    partyName: "저녁 요가 클래스",
    buildingAddr: "산성 실내 배드민턴장",
    streetAddr: "경기 수원시",
    date: "2025-05-04",
    startExerciseTime: "19:00:00",
    endExerciseTime: "20:30:00",
    femaleLevel: "초급",
    maleLevel: "누구나 참여 가능",
    nowMemberCnt: 7,
    maxMemberCnt: 12,
    includeParty: true,
    includeExercise: false,
    isFavorite: true,
  },
  {
    exerciseId: 3,
    partyName: "주말 필라테스",
    buildingAddr: "산성 실내 배드민턴장",
    streetAddr: "부산 해운대구",
    date: "2025-05-06",
    startExerciseTime: "08:30:00",
    endExerciseTime: "10:00:00",
    femaleLevel: "중급",
    maleLevel: "상급",
    nowMemberCnt: 3,
    maxMemberCnt: 8,
    includeParty: false,
    includeExercise: false,
    isFavorite: true,
  },
];
