export const groupDummy = [
  {
    partyId: 401,
    partyName: "민턴클로버",
    addr1: "경기도",
    addr2: "성남시",
    femaleLevel: "전국 초심 ~ 준자강",
    maleLevel: "전국 준자강 이상",
    latestExerciseDate: "2025-05-01",
    latestExerciseTime: "오전",
    exerciseCnt: 5,
    profileImgUrl: "src/assets/images/kitty.png",
    isFavorite: true,
  },
  {
    partyId: 402,
    partyName: "하이배드",
    addr1: "서울특별시",
    addr2: "강남구",
    femaleLevel: "초급 ~ 중급",
    maleLevel: "중급 ~ 상급",
    latestExerciseDate: "2025-05-03",
    latestExerciseTime: "오후",
    exerciseCnt: 3,
    profileImgUrl: "src/assets/images/kitty.png",
    isFavorite: true,
  },
  {
    partyId: 403,
    partyName: "셔틀콕즈",
    addr1: "인천광역시",
    addr2: "미추홀구",
    femaleLevel: "전국 초심",
    maleLevel: "전국 중급",
    latestExerciseDate: "2025-05-05",
    latestExerciseTime: "저녁",
    exerciseCnt: 6,
    profileImgUrl: "src/assets/images/kitty.png",
    isFavorite: true,
  },
  {
    partyId: 404,
    partyName: "민턴즈리턴",
    addr1: "수원시",
    addr2: "팔달구",
    femaleLevel: "전국 초심",
    maleLevel: "전국 중급",
    latestExerciseDate: "2025-05-05",
    latestExerciseTime: "저녁",
    exerciseCnt: 6,
    profileImgUrl: "src/assets/images/kitty.png",
    isFavorite: true,
  },
];
