export const groupDummy = [
  {
    id: 1,
    title: "민턴클로버",
    location: "경기도 / 성남시",
    femaleLevel: "전국 초심 ~ 준자강",
    maleLevel: "전국 준자강 이상",
    summary: "05.01 오전 운동 · 운동 5개 진행 예정",
    imageSrc: "src/assets/images/kitty.png",
    isFavorite: true,
  },
  {
    id: 2,
    title: "하이배드",
    location: "서울특별시 / 강남구",
    femaleLevel: "초급 ~ 중급",
    maleLevel: "중급 ~ 상급",
    summary: "05.03 오후 운동 · 운동 3개 예정",
    imageSrc: "src/assets/images/kitty.png",
    isFavorite: true,
  },
  {
    id: 3,
    title: "셔틀콕즈",
    location: "인천광역시 / 미추홀구",
    femaleLevel: "전국 초심",
    maleLevel: "전국 중급",
    summary: "05.05 저녁 운동 · 운동 6개 진행 예정",
    imageSrc: "src/assets/images/kitty.png",
    isFavorite: true,
  },
  {
    id: 4,
    title: "민턴즈리턴",
    location: "수원시 / 팔달구",
    femaleLevel: "전국 초심",
    maleLevel: "전국 중급",
    summary: "05.05 저녁 운동 · 운동 6개 진행 예정",
    imageSrc: "src/assets/images/kitty.png",
    isFavorite: true,
  },
];
