export { MyPage } from "./MyPage";
export { MyPageEditPage } from "./MyPageEditPage";
export { MyPageEditLocationPage } from "./MyPageEditLocationPage";
// export { MyPageExerciseDetailPage } from "./MyPageExerciseDetailPage";
export { MyPageMedalDetailPage } from "./MyPageMedalDetailPage";
export { MyPageMyExercisePage } from "./MyPageMyExercisePage";
export { MyPageMyGroupPage } from "./MyPageMyGroupPage";
export { MyPageMedalAddPage } from "./MyPageMedalAddpage";
export { MyPageAddressSearchPage } from "./MyPageAddressSearchPage";
export { MyPageProfileGroup } from "./MyPageProfileGroup";
export { MyPageProfileMedal } from "./MyPageProfileMedal";
export { MyPageProfile } from "./MyPageProfile";
export { default as MyPageMyMedalPage } from "./MyPageMyMedalPage";
